apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pandachain-miniapp-be.fullname" . }}
  labels:
    {{- include "pandachain-miniapp-be.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pandachain-miniapp-be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pandachain-miniapp-be.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      serviceAccountName: {{ include "pandachain-miniapp-be.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: monitoring
          containerPort: 9090
        - name: http
          containerPort: 5000
          protocol: TCP
        securityContext:
          {{- toYaml .Values.securityContext | nindent 14 }}
        command:
          {{- toYaml .Values.command | nindent 14 }}
        resources:
          {{- toYaml .Values.resources | nindent 14 }}
        envFrom:
          {{- toYaml .Values.envFrom | nindent 14 }}
      restartPolicy: {{ .Values.restartPolicy }}
