apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pandachain-miniapp-be.fullname" . }}
  labels:
    {{- include "pandachain-miniapp-be.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pandachain-miniapp-be.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: monitoring
