on:
  push:
    branches:
      - deploy
jobs:
  build:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set environment for branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/deploy' ]]; then
              echo "DEPLOY_NS=apps" >> "$GITHUB_ENV"
          else
              echo "DEPLOY_NS=staging" >> "$GITHUB_ENV"
          fi
      - name: Version
        id: version
        run: bin/version.sh
      - uses: EndBug/add-and-commit@v7
        if: github.ref == 'refs/heads/main'
        with:
          default_author: github_actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Add ssh key for multifarm-models
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          context: .
          file: ./infrastructure/Dockerfile
          push: true
          tags: multifarm/pandachain-miniapp-be:${{ steps.version.outputs.VERSION }}
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.9.0
      - name: Setup kubeconfig
        env:
          PROD_KUBECONFIG: ${{secrets.SCALEWAY_KUBECONFIG}}
        run: |
          echo "$PROD_KUBECONFIG" > kubeconfig
          chmod 400 kubeconfig
        shell: bash
      - name: Deploy Helmfile
        run: |
          export KUBECONFIG="$(pwd)/kubeconfig"
          ./bin/deploy.sh
